//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem
{


    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.Repeater rptUpcomingEvents;

        protected global::System.Web.UI.WebControls.Panel pnlNoEvents;
    }
}
